data:
  raw_path: "data/flights.csv"
  processed_path: '/data/gold/flight_weather.parquet'
  start_date: '2015-01-01'
  end_date: '2015-03-01'

model:
  type: 'RandomForest'
  n_trees: 100
  seed: 42

pipeline:
  load_columns:
    - 'YEAR'
    - 'MONTH'
    - 'DAY'
    - 'AIRLINE'
    - 'FLIGHT_NUMBER'
    - 'TAIL_NUMBER'
    - 'ORIGIN_AIRPORT'
    - 'DESTINATION_AIRPORT'
    - 'SCHEDULED_DEPARTURE'
    - 'DEPARTURE_TIME'
    - 'DEPARTURE_DELAY'
    - 'SCHEDULED_TIME'
    - 'ELAPSED_TIME'
    - 'AIR_TIME'
    - 'DISTANCE'
    - 'SCHEDULED_ARRIVAL'
    - 'ARRIVAL_TIME'
    - 'ARRIVAL_DELAY'
    - 'CANCELLED'


