source_schema:
    YEAR: 'int64'
    MONTH: 'int64'
    DAY: 'int64'
    DAY_OF_WEEK: 'int64'
    AIRLINE: 'object'
    FLIGHT_NUMBER: 'int64'
    TAIL_NUMBER: 'object'
    ORIGIN_AIRPORT: 'object'
    DESTINATION_AIRPORT: 'object'
    SCHEDULED_DEPARTURE: 'int64'
    DEPARTURE_TIME: 'float64'
    DEPARTURE_DELAY: 'float64'
    TAXI_OUT: 'float64'
    WHEELS_OFF: 'float64'
    SCHEDULED_TIME: 'float64'
    ELAPSED_TIME: 'float64'
    AIR_TIME: 'float64'
    DISTANCE: 'int64'
    WHEELS_ON: 'float64'
    TAXI_IN: 'float64'
    SCHEDULED_ARRIVAL: 'int64'
    ARRIVAL_TIME: 'float64'
    ARRIVAL_DELAY: 'float64'
    DIVERTED: 'int64'
    CANCELLED: 'int64'
    CANCELLATION_REASON: 'object'
    AIR_SYSTEM_DELAY: 'float64'
    SECURITY_DELAY: 'float64'
    AIRLINE_DELAY: 'float64'
    LATE_AIRCRAFT_DELAY: 'float64'
    WEATHER_DELAY: 'float64'

silver_schema:
  YEAR: 'int16'
  MONTH: 'int8'
  DAY: 'int8'
  AIRLINE: 'string'
  FLIGHT_NUMBER: 'int16'
  TAIL_NUMBER: 'string'
  ORIGIN_AIRPORT: 'string'
  DESTINATION_AIRPORT: 'string'
  SCHEDULED_DEPARTURE: 'float32'
  DEPARTURE_TIME: 'float32'
  DEPARTURE_DELAY: 'float32'
  SCHEDULED_TIME: 'float32'
  ELAPSED_TIME: 'float32'
  AIR_TIME: 'float32'
  DISTANCE: 'float32'
  SCHEDULED_ARRIVAL: 'float32'
  ARRIVAL_TIME: 'float32'
  ARRIVAL_DELAY: 'float32'
  CANCELLED: 'int8'

model_schema:
  YEAR: 'int16'
  MONTH: 'int8'
  DAY: 'int8'
  AIRLINE: 'category'
  FLIGHT_NUMBER: 'category'
  TAIL_NUMBER: 'category'
  ORIGIN_AIRPORT: 'category'
  DESTINATION_AIRPORT: 'category'
  SCHEDULED_DEPARTURE: 'float32'
  DEPARTURE_TIME: 'float32'
  DEPARTURE_DELAY: 'float32'
  SCHEDULED_TIME: 'float32'
  ELAPSED_TIME: 'float32'
  AIR_TIME: 'float32'
  DISTANCE: 'float32'
  SCHEDULED_ARRIVAL: 'float32'
  ARRIVAL_TIME: 'float32'
  ARRIVAL_DELAY: 'float32'